### ISSUE TITLE
Appli sympa !

### ISSUE THREAD

**Issue by L33Tpass** [Chonli/snow_weather_info#16]
Mon père l'a découverte via ski tour et moi ça m'a permis de découvrir flutter ! Merci pour le partage ça permet de tester pas mal de fonctionnalités ! 
Je ne savais pas où envoyer un commentaire alors je le fais là ^^

**Comment by Chonli** [comment]
@L33Tpass merci de ton commentaire, j'avais vu ton message mais j'avais pas vu que je pouvais te repondre. Oui en plus de m'être utile, l'application m'a permis de tester pas mal de fonctionnalité de Flutter. Si tu as des question sur mon code Flutter n'hésite pas.
